# username = input('请输入用户名：')
username = 'asd..wewq12321  '
print(username.isalnum())
print(username.isspace())
print(username.isalpha())
print(username.isdigit())
print(username.startswith('asd'))
print(username.endswith('123'))
print(username.split('.'))
print(username.find('.'))
print(username.index('.'))
print(username.lstrip())
print(username.rstrip())
print(username.strip())
print(username.ljust(20,'.'))
print(username.rjust(20,'.'))
print(username.center(20,'.'))
print(username.capitalize())
print(username.replace('1','5'))